# All entries in ${CURLY_BRACES} should be set as ENV variables, for security reasons.
# Learn more: https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html
frontend:
  root:
    url: http://localhost:5173/  #TODO Replace with your frontend root URL / empty string
logging:
  level:
    org:
      hibernate:
        SQL: debug
server:
  error:
    include-stacktrace: never
  port: 9000 # server port
  servlet:
    session:
      cookie:
        http-only: true
        max-age: 10800s #3hours
        name: WD_SESSION
    encoding:
      charset: UTF-8
      force: true
spring:
  datasource:
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://localhost:3306/wedemy?connectionTimeZone=UTC&useSSL=false
    username: root
  jpa:
    hibernate:
      ddl-auto: update #You may chnage to `NONE` in production
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          batch-size: 20
  cache:
    type: redis
    redis:
      time-to-live: PT30M #30minutes
  redis:
    host: localhost
    port: 6379
    password: ""
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  session:
    redis:
      cleanup-cron: 0 0 * * * *
      repository-type: indexed
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
#springdoc:
#  show-login-endpoint: true